# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - oidc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0' # Use a supported .NET version

      - name: Restore dependencies
        run: dotnet restore YourProjectName.csproj # Specify the project file

      - name: Build with dotnet
        run: dotnet build YourProjectName.csproj --configuration Release # Specify the project file

      - name: Test
        run: dotnet test YourProjectName.csproj --configuration Release # Specify the project file

      - name: dotnet publish
        run: dotnet publish YourProjectName.csproj -c Release -o ./deploy # Use a relative output path
        env:
          DOTNET_ROOT: !!null #remove this line

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./deploy

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C230B4FB884847DE8AD6961ABFB3F029 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B054EA5D4F75460B8B8FD5ACFE30E1DF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CE386416E9E44630A417D2C89CF1DCD3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'oidc'
          slot-name: 'Production'
          package: ./deploy # Deploy from the artifact directory

      - name: Azure App Service settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'oidc'
          slot-name: 'Production'
          app-settings-json: |
            [
              {"name": "ASPNETCORE_ENVIRONMENT", "value": "Production", "slotSetting": false}
            ]
